version: '3.1'

services:
  some-mysql: 
    image: mysql:9.0
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mysql-tp:/var/lib/mysql    
  mongo:
    image: mongo
    restart: always
    ports: 
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  notebook:
    image: grosinosky/bigdata_fila3_jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
    - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: yes
    command: start-notebook.py --NotebookApp.token=''      

volumes:
  mysql-tp: